#  注释
#1- 字典格式  键值对
#name: tom  # :后面要加空格
#password: “123456”
#2- 列表
#只要非数字都是别成字符串
#- 100
#- 200
#- 蓝色
#列表里套子列表
#- 100
#-
#  - 1
#  - 2
#  - 3

#3- 混合类型--字典套字典
#a: tom
#b:
#  c: 10
#  d: 20

#name: tom
#info:
#  - 10
#  - 20
#  - 30

#4- 引号用法 双引号、单引号
#a: hello\nworld
#b: 'hello\nworld' # 特殊字符，原格式输出——单引号
#c: "hello\nworld" # 转移后效果输出——双引号

#5- 引用变量
# '&'和’*‘ 用于引用
#info: &info naruto
#data:
#  - *info
#  - sq
#  - 200

#6- 可以用’---‘来分段，用for遍历取值
---  # 分隔符
name: tom
age: 20
---
name: Lily
age: 21
